# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e8be480b1433eed6be6214c0fa5b4fc08f54fee4fdb2d10a7368b1b5f26084d93fdc3a52a8b5b5cc40c9600b91c89892989935aa561873cfef3cce02141d56b4

test:
  secret_key_base: ac9ce03b6f5c63a9e71cdc87256bc9dfe1324eabc9232fa39a1fd6d0132fbc8ecb887517d357a74fbe8a8fd9cfb8b4dea07aeb5b6941d49ddb3d1644177cdb46

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
